Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: rj-bucket-1988
  Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0d06583a13678c938